export const tracks = [
    "A1 - Digital Transformation of Education - Data Science & AI in Education", 
    "A2 - Digital Transformation of Education - Learning Analytics", 
    "A3 - Digital Transformation of Education - Digital Technologies and Resources for Learning under Lockdown", 
    "A4 - Digital Transformation of Education - Digital Transformation", 
    "A5 - Digital Transformation of Education - 21st Century Skills", 
    "A6 - Digital Transformation of Education - Educational Programming & Robotics", 
    "B1 - Digital & Distance Learning - Distance Education in COVID-19 Times", 
    "B2 - Digital & Distance Learning - MOOCs & Open Educational Resources", 
    "B3 - Digital & Distance Learning - Blended & Mobile Learning", 
    "B4 - Digital & Distance Learning - e-Learning Experiences", 
    "B5 - Digital & Distance Learning - Learning Management Systems & Virtual Learning Environments", 
    "B6 - Digital & Distance Learning - Post-Pandemic Scenarios in Education", 
    "C1 - Innovative Educational Technologies - AI, Chatbots & Robots", 
    "C2 - Innovative Educational Technologies - Virtual & Augmented Reality", 
    "C3 - Innovative Educational Technologies - Technology Enhanced Learning", 
    "D1 - Multiculturality & Inclusion - Inclusive Education", 
    "D2 - Multiculturality & Inclusion - Special Educational Needs", 
    "D3 - Multiculturality & Inclusion - Multicultural Education", 
    "D4 - Multiculturality & Inclusion - Diversity Issues", 
    "E1 - Active & Student-Centered Learning - Gamification & Game-based Learning", 
    "E2 - Active & Student-Centered Learning - Active & Experiential Learning", 
    "E3 - Active & Student-Centered Learning - Problem & Project-Based Learning", 
    "E4 - Active & Student-Centered Learning - Pedagogical Innovations", 
    "E5 - Active & Student-Centered Learning - Soft Skills Development", 
    "F1 - Assessment, Mentoring & Student Support - Assessment & Evaluation", 
    "F2 - Assessment, Mentoring & Student Support - Rethinking Assessment in COVID-19 Times", 
    "F3 - Assessment, Mentoring & Student Support - Mentoring & Tutoring", 
    "F4 - Assessment, Mentoring & Student Support - Student Engagement & Wellbeing in COVID-19 Times", 
    "F5 - Assessment, Mentoring & Student Support - Student Support & Motivation", 
    "G1 - Educational Stages & Life-Long Learning - From Pre-school to Secondary Education", 
    "G2 - Educational Stages & Life-Long Learning - Higher Education & Labour Market Transition", 
    "G3 - Educational Stages & Life-Long Learning - Vocational Training", 
    "G4 - Educational Stages & Life-Long Learning - Non-formal Learning", 
    "G5 - Educational Stages & Life-Long Learning - Developing Entrepreneurship in Education", 
    "G6 - Educational Stages & Life-Long Learning - Life-long & Workplace Learning", 
    "H1 - Quality & Impact of Education - Quality in Education", 
    "H2 - Quality & Impact of Education - Curriculum Design Experiences", 
    "H3 - Quality & Impact of Education - Sustainability & Environmental Awareness", 
    "H4 - Quality & Impact of Education - Social Impact of Education", 
    "H5 - Quality & Impact of Education - University-Industry Collaboration", 
    "H6 - Quality & Impact of Education - Educational Trends & Globalisation", 
    "I1 - Teacher Training & Ed. Management - ICT & Digital Skills", 
    "I2 - Teacher Training & Ed. Management - Teacher Training and Support", 
    "I3 - Teacher Training & Ed. Management - Professional Development of Teachers", 
    "I4 - Teacher Training & Ed. Management - Educational Management", 
    "J1 - STEM Education - Mathematics & Statistics", 
    "J2 - STEM Education - Engineering Education", 
    "J3 - STEM Education - STEM Experiences", 
    "J4 - STEM Education - Computer Science", 
    "K1 - Language Learning and Teaching - Foreign Languages", 
    "K2 - Language Learning and Teaching - Language Learning & Translation Studies", 
    "K3 - Language Learning and Teaching - New Technologies in Language Learning", 
    "L1 - Discipline-Oriented Sessions - Architecture & Interior Design", 
    "L2 - Discipline-Oriented Sessions - Health Sciences Education", 
    "L3 - Discipline-Oriented Sessions - Business and Marketing Education", 
    "L4 - Discipline-Oriented Sessions - Legal Education"
]


export const topics = [
    "0.1 - COVID19: Distance Learning in Times of Crisis. From face-to-face to Remote Learning", 
    "0.2 - COVID19: Distance Learning in Times of Crisis. Digital Technologies and Resources for Learning under Lockdown", 
    "0.3 - COVID19: Distance Learning in Times of Crisis. Rethinking Assessment", 
    "0.4 - COVID19: Distance Learning in Times of Crisis. Teacher Training and Support", 
    "0.5 - COVID19: Distance Learning in Times of Crisis. Leadership and Management in Uncertain Times ", 
    "0.6 - COVID19: Distance Learning in Times of Crisis. Instructional Design and Curriculum Priorities", 
    "0.7 - COVID19: Distance Learning in Times of Crisis. Keeping Students Engaged", 
    "0.8 - COVID19: Distance Learning in Times of Crisis. Inclusion and Equity to Minimize the Educational Disruption", 
    "0.9 - COVID19: Distance Learning in Times of Crisis. Ensuring Students and Teachers Well-being", 
    "1.1 - Education: New Trends and Experiences. Education Practice Trends and Issues", 
    "1.2 - Education: New Trends and Experiences. Early Childhood Education", 
    "1.3 - Education: New Trends and Experiences. Primary and Secondary Education", 
    "1.4 - Education: New Trends and Experiences. Undergraduate Education", 
    "1.5 - Education: New Trends and Experiences. Post-graduate Education", 
    "1.6 - Education: New Trends and Experiences. Vocational Training", 
    "1.7 - Education: New Trends and Experiences. Adult Education", 
    "1.8 - Education: New Trends and Experiences. Informal Learning", 
    "1.9 - Education: New Trends and Experiences. Life-long learning", 
    "1.10 - Education: New Trends and Experiences. Employability Issues and Trends", 
    "2.1 - Pedagogical Methods and Innovations. Pedagogical Innovations", 
    "2.2 - Pedagogical Methods and Innovations. Flipped Learning", 
    "2.3 - Pedagogical Methods and Innovations. Collaborative and Problem-based Learning", 
    "2.4 - Pedagogical Methods and Innovations. Game-based Learning and Gamification", 
    "2.5 - Pedagogical Methods and Innovations. Active and Experiential Learning", 
    "2.6 - Pedagogical Methods and Innovations. Creativity and Design Thinking", 
    "2.7 - Pedagogical Methods and Innovations. Critical Thinking and Problem Solving", 
    "2.8 - Pedagogical Methods and Innovations. Language Learning Innovations", 
    "2.9 - Pedagogical Methods and Innovations. STEM Education Experiences", 
    "2.10 - Pedagogical Methods and Innovations. Tutoring and Mentoring", 
    "2.11 - Pedagogical Methods and Innovations. Assessment of Student Learning", 
    "2.12 - Pedagogical Methods and Innovations. Learning Space Design", 
    "2.13 - Pedagogical Methods and Innovations. 21st Century Skills", 
    "3.1 - Inclusive Learning, Cultural Diversity and Special Education. Barriers to Learning (ethnicity, age, etc.)", 
    "3.2 - Inclusive Learning, Cultural Diversity and Special Education. Gender and Equality in Education", 
    "3.3 - Inclusive Learning, Cultural Diversity and Special Education. Bullying Prevention and Awareness", 
    "3.4 - Inclusive Learning, Cultural Diversity and Special Education. Digital Divide and Technological Exclusion", 
    "3.5 - Inclusive Learning, Cultural Diversity and Special Education. Multicultural Inclusion and Indigenous Perspectives", 
    "3.6 - Inclusive Learning, Cultural Diversity and Special Education. Refugees, Migrants and Minorities Inclusion", 
    "3.7 - Inclusive Learning, Cultural Diversity and Special Education. Educating Individuals with Sensory and Motor Disabilities", 
    "3.8 - Inclusive Learning, Cultural Diversity and Special Education. Educating Individuals with Intellectual Disabilities", 
    "3.9 - Inclusive Learning, Cultural Diversity and Special Education. Lifespan Transitions and Employability", 
    "3.10 - Inclusive Learning, Cultural Diversity and Special Education. Universal Design for Learning", 
    "3.11 - Inclusive Learning, Cultural Diversity and Special Education. Assistive Technologies and Accessible Resources", 
    "4.1 - New Challenges in Education and International Cooperation. New challenges for the Higher Education Area", 
    "4.2 - New Challenges in Education and International Cooperation. Students and Teaching Staff Exchange Programmes", 
    "4.3 - New Challenges in Education and International Cooperation. Erasmus+ Programme Experiences", 
    "4.4 - New Challenges in Education and International Cooperation. The Bologna Process and ECTS Experiences", 
    "4.5 - New Challenges in Education and International Cooperation. International Projects", 
    "4.6 - New Challenges in Education and International Cooperation. New experiences for the International Cooperation", 
    "4.7 - New Challenges in Education and International Cooperation. Joint Education and Research Programmes 4.8 New Challenges in Education and International Cooperation. University Networks", 
    "5.1 - Teacher Training. Pre-service Teacher Experiences", 
    "5.2 - Teacher Training. In-service Teacher Training", 
    "5.3 - Teacher Training. Professional Development of Teachers", 
    "5.4 - Teacher Training. ICT Skills Development", 
    "5.5 - Teacher Training. Teacher Leaders", 
    "6.1 - Curriculum Design. New Experiences for Curriculum Design", 
    "6.2 - Curriculum Design. Strategies, Principles and Challenges", 
    "6.3 - Curriculum Design. Courses, Tutorials and Labs", 
    "6.4 - Curriculum Design. Multidisciplinary Studies", 
    "6.5 - Curriculum Design. Generic Skills and their Development", 
    "6.6 - Curriculum Design. Skill Needs of Labour Market", 
    "7.1 - Accreditation and Quality in Education. Academic Experiences and Best Practice Contributions", 
    "7.2 - Accreditation and Quality in Education. Quality Processes at National and International Level", 
    "7.3 - Accreditation and Quality in Education. Evaluation and Assessment", 
    "7.4 - Accreditation and Quality in Education. Student Selection Criteria", 
    "7.5 - Accreditation and Quality in Education. Plagiarism in Education and Detection Strategies", 
    "8.1 - Research: New Trends and Experiences. Research Methodologies", 
    "8.2 - Research: New Trends and Experiences. Academic Research Projects", 
    "8.3 - Research: New Trends and Experiences. Research on Technology in Education", 
    "8.4 - Research: New Trends and Experiences. Research Centres and Programmes", 
    "8.5 - Research: New Trends and Experiences. Links between Education and Research", 
    "8.6 - Research: New Trends and Experiences. Research Management", 
    "9.1 - University-Industry Cooperation. University/Industry Experiences", 
    "9.2 - University-Industry Cooperation. Workplace Learning", 
    "9.3 - University-Industry Cooperation. Work Employability", 
    "9.4 - University-Industry Cooperation. Entrepreneurship Education", 
    "9.5 - University-Industry Cooperation. University/Industry/Government partnership", 
    "9.6 - University-Industry Cooperation. Technology Transfer and Patents", 
    "9.7 - University-Industry Cooperation. University Spin-offs and Start-ups", 
    "10.1 - Global Issues in Education and Research. Education, Research and Globalization", 
    "10.2 - Global Issues in Education and Research. Organizational, Legal and Financial Aspects", 
    "10.3 - Global Issues in Education and Research. Government Policy Issues", 
    "10.4 - Global Issues in Education and Research. Impact of Economic Crisis on Education", 
    "10.5 - Global Issues in Education and Research. Ethical Issues in Education", 
    "10.6 - Global Issues in Education and Research. Education for Sustainability", 
    "10.7 - Global Issues in Education and Research. Leadership and Educational Management", 
    "10.8 - Global Issues in Education and Research. Student Support and Motivation", 
    "10.9 - Global Issues in Education and Research. Community Engagement and Youth participation", 
    "11.1 - Technology in Teaching and Learning. Learning and Teaching Innovations", 
    "11.2 - Technology in Teaching and Learning. e-Learning Experiences", 
    "11.3 - Technology in Teaching and Learning. m-Learning: Mobile Applications and Technologies", 
    "11.4 - Technology in Teaching and Learning. Blended Learning and Flipped Classroom", 
    "11.5 - Technology in Teaching and Learning. Advanced Classroom Applications and Technologies", 
    "11.6 - Technology in Teaching and Learning. Next Generation Classroom", 
    "11.7 - Technology in Teaching and Learning. Online/Virtual Laboratories", 
    "11.8 - Technology in Teaching and Learning. Open Universities and Distance Education", 
    "11.9 - Technology in Teaching and Learning. Massive Open Online Courses (MOOC)", 
    "11.10 - Technology in Teaching and Learning. Online Assessment", 
    "11.11 - Technology in Teaching and Learning. e-Tutoring", 
    "11.12 - Technology in Teaching and Learning. Virtual Learning Environments (VLE)", 
    "11.13 - Technology in Teaching and Learning. Learning Management Systems (LMS)", 
    "11.14 - Technology in Teaching and Learning. ICT and Digital Skills", 
    "11.15 - Technology in Teaching and Learning. Educating the Educators", 
    "11.16 - Technology in Teaching and Learning. Building Virtual Communities", 
    "12.1 - Emerging Technologies in Education. Web 2.0 and Social Networking", 
    "12.2 - Emerging Technologies in Education. Social and Digital Media", 
    "12.3 - Emerging Technologies in Education. Educational/Serious Games and Software", 
    "12.4 - Emerging Technologies in Education. Videos for Learning and Educational Multimedia", 
    "12.5 - Emerging Technologies in Education. Animation and 3D Applications", 
    "12.6 - Emerging Technologies in Education. Virtual and Augmented Reality", 
    "13.1 - E-content Management and Development. Digital Libraries and Repositories", 
    "13.2 - E-content Management and Development. e-Portfolios", 
    "13.3 - E-content Management and Development. User-Generated Content", 
    "13.4 - E-content Management and Development. Open Educational Resources", 
    "13.5 - E-content Management and Development. Learning Analytics", 
    "13.6 - E-content Management and Development. Plagiarism and Intellectual Property Rights", 
    "13.7 - E-content Management and Development. Knowledge Management"
]



export const disciplines = [
    "1 - Accounting & Finance", 
    "2 - Actuarial Science", 
    "3 - Adult and Vocational Education", 
    "4 - Aeronautics and Astronautics", 
    "5 - Agricultural Engineering", 
    "6 - Agricultural Science ", 
    "7 - Anthropology ", 
    "8 - Architecture & Urban Planning", 
    "9 - Art & Humanities", 
    "10 - Astronomy ", 
    "11 - Biochemistry", 
    "12 - Bioengineering", 
    "13 - Biology", 
    "14 - Biotechnology", 
    "15 - Business Adm.& Mgmt. / Business Studies", 
    "16 - Chemical Engineering", 
    "17 - Chemistry", 
    "18 - Civil Engineering", 
    "19 - Classical Languages", 
    "20 - Communications & Media Studies", 
    "21 - Computer Science and Engineering", 
    "22 - Dance", 
    "23 - Drama & Theatre Studies", 
    "24 - Early Childhood Education", 
    "25 - Economics", 
    "26 - Education ", 
    "27 - Electrical Engineering & Electronics ", 
    "28 - Engineering: Others", 
    "29 - Environmental Science and Engineering", 
    "30 - Fine Arts", 
    "31 - Food Science and Technology", 
    "32 - Foreign Languages", 
    "33 - Geosciences / Earth Sciences", 
    "34 - Graphic & Industrial Design", 
    "35 - Health & Wellness", 
    "36 - History", 
    "37 - Industrial Engineering", 
    "38 - International Studies", 
    "39 - Journalism", 
    "40 - Law", 
    "41 - Library and Resource Management", 
    "42 - Life & Health Sciences: Others", 
    "43 - Linguistics ", 
    "44 - Literature", 
    "45 - Marketing ", 
    "46 - Materials Science and Engineering", 
    "47 - Mathematics & Statistics", 
    "48 - Mechanical Engineering", 
    "49 - Medicine", 
    "50 - Music Education ", 
    "51 - Nanotechnology", 
    "52 - Nuclear Science and Engineering", 
    "53 - Nursing", 
    "54 - Nutritional Science / Dietetics", 
    "55 - Odontology", 
    "56 - Optics and Optometry", 
    "57 - Others", 
    "58 - Pedagogy", 
    "59 - Pharmacy", 
    "60 - Philosophy", 
    "61 - Physical Education and Sports", 
    "62 - Physics", 
    "63 - Physiotherapy", 
    "64 - Politics / Political Science", 
    "65 - Primary Education", 
    "66 - Psychology", 
    "67 - Psycho-Pedagogy", 
    "68 - Secondary Education", 
    "69 - Social Education", 
    "70 - Social Work Education", 
    "71 - Special Education", 
    "72 - Telecommunications Engineering", 
    "73 - Theology & Religious Studies", 
    "74 - Tourism", 
    "75 - Veterinary Sciences"
]